### ISSUE TITLE
Teamspeak3 flatpak version got updated to Teamspeak5

### ISSUE THREAD

**Issue by Exiphi** [flathub/com.teamspeak.TeamSpeak#52]
Hello!

It seems like the TeamSpeak3 Flatpak got updated to the TeamSpeak5 version today for some reason. 

I'm a newbie and not quite sure how to file one of these correctly, but I got pointed here so I'm giving it a shot!

**Comment by func0der** [comment]
If that was on purpose it would be great to get the old version under a dedicated name back. TeamSpeak 5 is still in Beta and until the Beta is not over it can not become "TeamSpeak" :D

**Comment by Exiphi** [comment]
After a bit more research it seems like they are cross compatible, someone said they were not so I believed them. That's why I thought this seemed so weird.

I still think TS3 and TS5 should probably be separate tho, but maybe that introduces other problems.

**Comment by Zlopez** [comment]
I had the TeamSpeak5 in Beta branch for some time and it was without issue. So I decided to update it as it's the one recommended by TeamSpeak itself. If you go to [their page](https://teamspeak.com/) the TeamSpeak5 is the one you get redirected to on donwload page. So even TeamSpeak company is confident enough to make this a default one.

**Comment by Zlopez** [comment]
You can always request a TeamSpeak3 repository on Flathub, if you want to have it around.

**Comment by func0der** [comment]
> So even TeamSpeak company is confident enough to make this a default one.

I mean "confident" is the one thing. But you could also argue, that they just want to collect more data,  be it for beta evaluating or for selling it doesn't matter. You are currently forced to have an account with them to participate in their "beta". 

In this flatpak "beta" software is sold as stable, which is a weird and confusing way of dealing with things.
Since you are the maintainer and you can basically do whatever you want that is up to you of course, but I for once was very confused to see a completely new app when I tried to open TeamSpeak. An app that I and maybe others purposely try to avoid BECAUSE of their interesting definition of "BETA".

The client also does not have any notices about privacy policies, an imprint or similar documents required by law to agree to before you open an account with them. Therefore I highly doubt that its delivery in the current state is legal by any state inside the EU.

Also there is barely future parity with the TS3 client as far as I know. I have not tested this myself yet to an extend where I can confidently say that this is 100% true. It is hearsay.

Also I could not test any of it, since the account creation in the TS5 client is broken for me as of right now.

I urge you to please reconsider your decision to offer BETA software as a STABLE representation of said software.

I do not say: do not put TS5 out there on Flathub, but instead of having the current stable and working piece of software kicked off a well known namespace for a beta client, why not publish the beta client on a dedicated namespace UNTIL it becomes the real new stable client?
Yet again, I would strongly advice against selling beta as stable, but it would influence less people in a suprising way.

Or just keep using the `beta` branch approach. :D

**Comment by func0der** [comment]
> In case anyone doesn't want to create an account, to go back to TS3 and lock the version of the Flatpak use these 2 commands:

Thanks for the suggestion, but please explain such things.
Flatpak is not really meant to run with sudo, if not needed and where is that commit hash comming from?

**Comment by DomiStyle** [comment]
> Flatpak is not really meant to run with sudo, if not needed

It is not allowed to downgrade packages without root permissions.

> where is that commit hash comming from?

`flatpak remote-info --log flathub com.teamspeak.TeamSpeak` shows the past versions, including commit hashes.

**Comment by Zlopez** [comment]
Actually I got requests to update to TeamSpeak 5 as this is the official version of TS provided on TeamSpeak page and people were confused that it's not the same. So if I go back I will see the same issue as now just for people complaining why I'm providing TS3 when TS5 is available.

There is nothing preventing anyone to request a TeamSpeak 3 repository on Flathub and have the TeamSpeak 3 as a separate application, same as it is on the TeamSpeak page.

**Comment by DomiStyle** [comment]
No worries, not your fault. It's Teamspeak's fault for releasing a beta software as default that requires an account.

TS3 flatpak seems to be on the way so all is good. Thanks for maintaining the Flatpak!

Also, this might be a good point in time to switch to an open source alternative that doesn't pretend to be Discord: [Mumble](https://www.mumble.info/)

**Comment by Zlopez** [comment]
@DomiStyle I can only recommend Mumble it's a good piece of software

**Comment by LeonMarcel-HD** [comment]
This is not the way it should be!

TS3 uses a different database than TS5 and is therefore not compatible. @Exiphi said both clients are compatible but this is only applicable to the servers and NOT the clients itself.

I don't use TS5 since 2020 and I'm even though I think people should move... They should move on their own and not by updating a software to a new one which is NOT the same client as they downloaded.

TS5 should have gotten their own application and not the other way around. If this will not be reverted it will lead to frustration among many TS users. Been talking to a TeamSpeak employee about this and this is what he stated:

**The TS3 database is not compatible with TS5 and we would never force TS3 users to update this way!**

**Comment by chrisTeamSpeak** [comment]
I can only agree to @LeonMarcel-HD 

Updating from TS3 to TS5 with same files is nothing we from TeamSpeak will support. They should be handled as different package.
Our `settings.db` from TS3 client can not be used for the TS5. They differ in several areas and will break the TS5 client.

**Comment by Exiphi** [comment]
> This is not the way it should be!
> 
> TS3 uses a different database than TS5 and is therefore not compatible. @Exiphi said both clients are compatible but this is only applicable to the servers and NOT the clients itself.
> 
> I don't use TS5 since 2020 and I'm even though I think people should move... They should move on their own and not by updating a software to a new one which is NOT the same client as they downloaded.
> 
> TS5 should have gotten their own application and not the other way around. If this will not be reverted it will lead to frustration among many TS users. Been talking to a TeamSpeak employee about this and this is what he stated:
> 
> **The TS3 database is not compatible with TS5 and we would never force TS3 users to update this way!**

What I meant was simply that I was able to connect to TS3 servers on the TS5 client which I thought wasn't possible at first. Sorry if I used the wrong wording.

**Comment by Zlopez** [comment]
There is already a work being done on [TS3 version for flathub](https://github.com/flathub/flathub/pull/4851). It will be a separate application as requested, this repository will stay as TS5. I'm sorry this caused so many issues.

**Comment by dnkr1337** [comment]
@DomiStyle 

> sudo flatpak mask com.teamspeak.TeamSpeak

it seems that masking doesn't work in my case, I manually downgrade to TS3 and everything works, but the next day after starting the computer I have TS5 again. Do you think it's a flatpak bug or my individual problem?

**Comment by DomiStyle** [comment]
@dnkr1337 No idea unfortunately.

Masking works fine for me on Fedora. I'm still on TS3 even though I update almost daily.

**Comment by func0der** [comment]
> it seems that masking doesn't work in my case, I manually downgrade to TS3 and everything works, but the next day after starting the computer I have TS5 again. Do you think it's a flatpak bug or my individual problem?

Do it without `sudo` and maybe `flatpak --user` instead. I am not sure, but with `sudo` it probably either does it for the `root` user or for the system, which is probably both not wanted on your part.
