### ISSUE TITLE
Flatpak updated to beta Teamspeak5 and requires login

### ISSUE THREAD

**Issue by faeyben** [flathub/com.teamspeak.TeamSpeak#54]
Hello,

today my flatpak installation of Teamspeak 3 updated to Teamspeak 5.  

Teamspeak 5 is still marked as a beta version and requires a Teamspeak account to use it (it is explicitly marked as necessary for the beta access so that requirement will probably go away when the beta ends).

Due to that, I suggest that the teamspeak version on flathub should be kept at Teamspeak 3 until Teamspeak 5 is out of beta.  
Alternatively, TS5 could have been added as an additional software for those that want to update to a beta version already.

Regards

**Comment by LeonMarcel-HD** [comment]
As already mentioned in #52 it should not be updated at all as the database is NOT compatible due to the fact that it is a new client and not an update. TS5 should get their own flatpak and should not be forcely updated for TS3 users.

https://github.com/flathub/com.teamspeak.TeamSpeak/issues/52#issuecomment-1889649546

**Comment by faeyben** [comment]
I see an issue with active discussion about this already exists (even if it is Closed), sorry for opening a new one.

**Comment by LeonMarcel-HD** [comment]
You shouldn't be sorry as this has to be resolved as soon as possible!
